---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: custom-es
  namespace: default
  labels:
      app: elasticsearch-custom
      role: data
spec:
  serviceName: elasticsearch-custom
  replicas: 1
  selector:
      matchLabels:
          role: data
  template:
    metadata:
      labels:
        app: elasticsearch-custom
        role: data
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: aws-managed-disk
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      containers:
      - name: custom-es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.name
          value: custom-es
        - name: node.master
          value: "true"
        - name: node.data
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms500m -Xmx500m
        - name: path.logs
          value: /var/log
        - name: path.data
          value: /usr/share/elasticsearch/data
        - name: xpack.security.enabled
          value: "false"
        - name: path.repo
          value: /usr/share/
        - name: discovery.zen.ping.unicast.hosts
          value: elasticsearch-custom
        - name: discovery.type
          value: "single-node"
        ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 9300
          protocol: TCP
        volumeMounts:
        - mountPath: "/usr/share/elasticsearch/data"
          name: aws-managed-disk
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: aws-managed-disk
        labels:
          app: elasticsearch
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

---
kind: Service
apiVersion: v1
metadata:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    namespace: default
    name: elasticsearch-custom
    labels:
      app: elasticsearch-custom
      role: data
spec:
    type: LoadBalancer
    selector:
      role: data
    ports:
    - name: rest-port
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: node-port
      protocol: TCP
      port: 9300
      targetPort: 9300
