apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    # all input will come from filebeat, no local logs
    input {
      beats {
        port => 5044
      }
      s3 {
        "access_key_id" => "AWS_ACCESS_KEY_ID"
        "secret_access_key" => "AWS_SECRET_ACCESS_KEY"
        "bucket" => "ec1-dev-toptal-cicd-s3"
        "region" => "eu-central-1"
      }
    }
    filter {
    }
    output {
      elasticsearch {
        index => "logstash-%{+YYYY.MM.dd}"
        hosts => [ "${ES_HOSTS}" ]
      }
    }
